services:
  app:
    build: .
    container_name: python-server
    command: sleep infinity
    ports:
      - 88:88
    volumes:
      - .:/code
    devices:
      - /dev/video0:/dev/video0
    # depends_on:
    #   - redis